// module-4/vue-training/src/components/IdCard.vue
<template>
  <div class="card">
    <img class="img" :src="picture" alt="a cool pic" />
    <p class="infos">
      First name : {{ firstName }} <br />
      Last name : {{ lastName }} <br />
      Gender : {{ gender }} <br />
      Height : {{ height }} <br />
      birth :
      {{
        birth.toLocaleString("en-US", {
          weekday: "short",
          year: "numeric",
          month: "short",
          day: "numeric",
        })
      }}
      <br />
    </p>
  </div>
</template>

<script setup>
defineProps({
  lastName: String,
  firstName: String,
  gender: String,
  height: Number,
  birth: Date,
  picture: String,
});
</script>

<style scoped>
.card {
  border: 1px solid;
  display: flex;
  justify-content: space-between;
  margin-bottom: 10px;
  height: 128px;
}

.img {
  width: 128px;
  height: 100%;
}

.infos {
  flex: 1;
  padding: 10px;
}
</style>

// module-3/week-1/lab-proposal-solutions/lab-react-training/src/components/IdCard.jsx
const convertCentimetersToMeter = (value) => value / 100;

function IdCard({ lastName, firstName, gender, height, birth, picture }) {
  const date = birth.toDateString();
  return (
    <>
      <div className="container">
        <div className="user-picture-wrapper">
          <img src={picture} alt="user" />
        </div>
        <div className="IdCard content">
          <p>
            <span className="bold">First name: </span>
            {firstName}
          </p>
          <p>
            <span className="bold">Last name: </span>
            {lastName}
          </p>
          <p>
            <span className="bold">Gender: </span>
            {gender}
          </p>
          <p>
            <span className="bold">Height: </span>
            {convertCentimetersToMeter(height)}m
          </p>
          <p>
            <span className="bold">Birth: </span>
            {date}
          </p>
        </div>
      </div>
    </>
  );
}

export default IdCard;
